name: GolfSwingCoach
options:
  bundleIdPrefix: com.golfswing
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: minimal
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  GolfSwingCoach:
    type: application
    platform: iOS
    sources:
      - path: GolfSwingCoach
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.golfswing.coach
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Golf Swing Coach needs access to your photos to analyze swing videos"
        INFOPLIST_KEY_NSCameraUsageDescription: "Golf Swing Coach can record swing videos for analysis"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
